import fs from "node:fs/promises";
import type { ApplyResult, ProviderId, ProviderProfile } from "../../shared/types";
import { buildOpenClawConfig, resolveDefaultModel } from "../../shared/profile";
import { CredentialService } from "./credentialService";
import { getPresetFilePath } from "./pathResolver";
import { WslService } from "./wslService";

const MODEL_BY_PROVIDER: Record<ProviderId, string> = {
  deepseek: "deepseek-chat",
  openai: "gpt-4.1-mini",
  anthropic: "claude-3-5-haiku-latest",
  perplexity: "sonar"
};

type PresetsFile = {
  defaults?: {
    defaultModel?: string;
    fallbackChain?: ProviderId[];
  };
};

export class ConfigService {
  constructor(
    private readonly credentials: CredentialService,
    private readonly wslService: WslService
  ) {}

  async applyProfile(profile: ProviderProfile): Promise<ApplyResult> {
    const configured = await this.credentials.listConfigured();
    if (configured.length === 0) {
      return {
        ok: false,
        message: "No configured providers. Add at least one API key first."
      };
    }

    const defaults = await this.loadPresetDefaults();
    const enabledProviders = configured.filter((provider) =>
      profile.enabledProviders.includes(provider)
    );

    const requestedFallback = profile.fallbackChain.filter((provider) =>
      enabledProviders.includes(provider)
    );
    const fallbackChain = requestedFallback.length > 0 ? requestedFallback : defaults.fallbackChain;

    const chosenModel = this.pickModel(profile.defaultModel, enabledProviders, defaults.defaultModel);

    const patch = buildOpenClawConfig({
      ...profile,
      enabledProviders,
      fallbackChain,
      defaultModel: chosenModel
    });

    const envContent = await this.buildEnvContent(enabledProviders);
    const configContent = this.buildConfigContent(patch.defaultModel, patch.providers, patch.tools);

    await this.wslService.ensureOpenClawDirectory();
    await this.wslService.writeOpenClawFile(".env", envContent);
    await this.wslService.writeOpenClawFile("openclaw.json", configContent);

    return {
      ok: true,
      message: `Applied profile with default model ${chosenModel}.`
    };
  }

  async applyDefaultProfile(searchEnabled: boolean): Promise<ApplyResult> {
    const configured = await this.credentials.listConfigured();
    const preferred = configured.filter((provider) => provider !== "perplexity");
    const defaultModel = resolveDefaultModel(preferred);

    const fallbackChain: ProviderId[] = ["deepseek", "openai", "anthropic"];
    return this.applyProfile({
      enabledProviders: configured,
      defaultModel,
      fallbackChain,
      searchEnabled
    });
  }

  private async loadPresetDefaults(): Promise<{
    defaultModel: string;
    fallbackChain: ProviderId[];
  }> {
    try {
      const raw = await fs.readFile(getPresetFilePath(), "utf8");
      const parsed = JSON.parse(raw) as PresetsFile;
      return {
        defaultModel: parsed.defaults?.defaultModel ?? "deepseek-chat",
        fallbackChain: parsed.defaults?.fallbackChain ?? ["deepseek", "openai", "anthropic"]
      };
    } catch {
      return {
        defaultModel: "deepseek-chat",
        fallbackChain: ["deepseek", "openai", "anthropic"]
      };
    }
  }

  private pickModel(
    requestedModel: string,
    enabledProviders: ProviderId[],
    defaultFromPreset: string
  ): string {
    if (requestedModel?.trim()) {
      return requestedModel.trim();
    }

    const first = enabledProviders.find((provider) => provider !== "perplexity");
    if (!first) {
      return defaultFromPreset;
    }
    return MODEL_BY_PROVIDER[first] ?? defaultFromPreset;
  }

  private async buildEnvContent(enabledProviders: ProviderId[]): Promise<string> {
    const lines: string[] = [
      "# Generated by OpenClaw Desktop",
      `# ${new Date().toISOString()}`
    ];

    for (const provider of enabledProviders) {
      const key = await this.credentials.get(provider);
      if (!key) {
        continue;
      }
      switch (provider) {
        case "deepseek":
          lines.push(`DEEPSEEK_API_KEY=${key}`);
          break;
        case "openai":
          lines.push(`OPENAI_API_KEY=${key}`);
          break;
        case "anthropic":
          lines.push(`ANTHROPIC_API_KEY=${key}`);
          break;
        case "perplexity":
          lines.push(`PERPLEXITY_API_KEY=${key}`);
          break;
        default:
          break;
      }
    }

    return `${lines.join("\n")}\n`;
  }

  private buildConfigContent(
    defaultModel: string,
    providers: Record<string, unknown>,
    tools: Record<string, unknown>
  ): string {
    const payload = {
      generatedBy: "OpenClaw Desktop",
      generatedAt: new Date().toISOString(),
      model: defaultModel,
      providers,
      tools
    };
    return `${JSON.stringify(payload, null, 2)}\n`;
  }
}
